### ISSUE TITLE
Add world saving/loading

### ISSUE THREAD

**Issue by Unarelith** [Unarelith/OpenMiner#26]
See #122.

**Comment by Unarelith** [comment]
Partially fixed by https://github.com/Unarelith/OpenMiner/commit/a3554552ed09c7493c34f9082664dfa1ab85a01e

**Comment by Unarelith** [comment]
Missing features have their own tickets:
- [ ] Save entities (see #126)
- [ ] Save player positions and inventories (see #127)
- [ ] Save seed (see #116)
- [ ] Improve `WorldSelectionState` and `WorldInfoState` (see #128)
